@echo off
echo ================================================
echo    EmailJS Setup for Portfolio Contact Form
echo ================================================
echo.
echo This script will help you create your .env file
echo.
echo First, you need to:
echo 1. Go to https://www.emailjs.com/
echo 2. Create a FREE account
echo 3. Add an email service (Gmail recommended)
echo 4. Create an email template
echo 5. Get your credentials
echo.
pause
echo.
echo Enter your EmailJS credentials:
echo.
set /p SERVICE_ID="Service ID: "
set /p TEMPLATE_ID="Template ID: "
set /p PUBLIC_KEY="Public Key: "
echo.
echo Creating .env file...
(
echo # EmailJS Configuration
echo # Auto-generated by setup_emailjs.bat
echo VITE_EMAILJS_SERVICE_ID=%SERVICE_ID%
echo VITE_EMAILJS_TEMPLATE_ID=%TEMPLATE_ID%
echo VITE_EMAILJS_PUBLIC_KEY=%PUBLIC_KEY%
) > .env
echo.
echo ================================================
echo    .env file created successfully!
echo ================================================
echo.
echo Your contact form is now configured!
echo Run 'npm run dev' to test it.
echo.
echo NOTE: Make sure to test the form to verify everything works.
echo.
pause
